version: '3.8'

services:
  spark_master_one:
    image: bitnami/spark:3.5.1
    container_name: spark_master_one
    ports:
      - "8190:8080"
      - "7077:7077"
    environment:
      SPARK_UI_PORT: 8080
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    volumes:
      - ./spark/scripts:/opt/bitnami/spark/scripts
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.2

  #SALES stream
  spark_worker_first_one:
    image: bitnami/spark:3.5.1
    container_name: spark_worker_first_one
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://172.30.0.2:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    volumes:
      - ./spark/scripts/sales:/opt/bitnami/spark/scripts
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.3

  #WAREHOUSE stream
  spark_worker_second_one:
    image: bitnami/spark:3.5.1
    container_name: spark_worker_second_one
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://172.30.0.2:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    volumes:
      - ./spark/scripts/warehouse:/opt/bitnami/spark/scripts
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.4

  zookeeper_one:
    image: zookeeper:3.5.9
    container_name: zookeeper_one
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.30.0.3:2888:3888;2181
      ZOO_PORT: 2181
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.5

  kafka_first_one:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_first_one
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 172.30.0.5:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.0.6:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000 #1 day in milliseconds
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper_one
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.6

  kafka_second_one:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_second_one
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 172.30.0.5:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.0.7:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000 #1 day in milliseconds
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper_one
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.7

  kafka_third_one:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_third_one
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 172.30.0.5:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.0.8:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000 #1 day in milliseconds
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper_one
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.8

  cassandra_one:
    build: ./cassandra
    container_name: cassandra_one
    hostname: cassandra_one
    environment:
      CASSANDRA_START_RPC: true
      CASSANDRA_CLUSTER_NAME: cassandra_dashboard_one
    ports:
      - '9042:9042'
    volumes:
      - ./cassandra/init_db:/initdb
      - cassandra_data:/var/lib/cassandra
      - cassandra_logs:/var/log/cassandra
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.9

  api_python:
    build: ./api_python
    container_name: api_one
    hostname: api_one
    depends_on:
      - kafka_first_one
      - kafka_second_one
      - kafka_third_one
      - zookeeper_one
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.10

  dashboard_one:
    build: ./dashboard
    container_name: dashboard_one
    hostname: dashboard_one
    ports:
      - "8900:5000"
    networks:
      dashboard_one:
        ipv4_address: 172.30.0.11


volumes:
  cassandra_data: {}
  cassandra_logs: {}
  kafka_data: {}

networks:
  dashboard_one:
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: "172.30.0.0/16"