version: '3.8'

services:  
  spark_one:
    image: docker.io/bitnami/spark:3
    container_name: spark_master
    hostname: spark_master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8085:8080'
    volumes:
      - ./spark/jars:/opt/bitnami/spark/ivy:z
      - ./spark/scripts:/opt/bitnami/spark/scripts
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.2

  zookeeper_one:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.3

  kafka_one:
    image: ./kafka/Dockerfile
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.4

  cassandra_one:
    image: ./cassandra/Dockerfile
    container_name: cassandra
    hostname: cassandra
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=cassandra_dashboard_one
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
      - cassandra_logs:/var/log/cassandra
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.5

  dashboard_one:
    image: python:3.10
    ports:
      - "8900:5000"
    volumes:
      - ./dashboard:/usr/src/app
    working_dir: /usr/src/app
    command: python dashboard.py
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.6

  flask_one:
    image: python:3.10
    ports:
      - "5001:5000"
    volumes:
      - ./python_scripts:/usr/src/app
    working_dir: /usr/src/app
    command: python random_data.py
    environment:
      - FLASK_ENV=development
    networks:
      dashboard_one:
        ipv4_address: 172.18.0.7

volumes:
  cassandra_data: {}
  cassandra_logs: {}

networks:
    dashboard_one:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"